<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NetCraft.Registry\NetCraft.Registry.csproj" />
    <ProjectReference Include="..\NetCraft.Storage\NetCraft.Storage.csproj" />
    <ProjectReference Include="..\NetCraft.Resources\NetCraft.Resources.csproj" />
    <ProjectReference Include="..\NetCraft.Tags\NetCraft.Tags.csproj" />
    <ProjectReference Include="..\NetCraft.Network\NetCraft.Network.csproj" />
    <ProjectReference Include="..\NetCraft.Commands\NetCraft.Commands.csproj" />
    <ProjectReference Include="..\NetCraft.Gpu\NetCraft.Gpu.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
