<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NetCraft.Primitives\NetCraft.Primitives.csproj" />
    <ProjectReference Include="..\NetCraft.Config\NetCraft.Config.csproj" />
    <ProjectReference Include="..\NetCraft.Codec\NetCraft.Codec.csproj" />
    <ProjectReference Include="..\NetCraft.Util\NetCraft.Util.csproj" />
    <ProjectReference Include="..\NetCraft.Interop\NetCraft.Interop.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
