using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NetCraft.DataFixer.SourceGenerator;

//扫描继承NetCraft.DataFixer.Types.Type<A>的具体类生成TypeObjectConverterFactory
//对齐Java类型擦除下Type<A>等价Type<Object>的语义提供AsObjectType转换入口
//当前为最小可行版本只生成默认转换实现后续逐步添加专用case
[Generator]
public class TypeObjectConverterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        //扫描所有ClassDeclarationSyntax过滤继承Type<A>的具体类
        var subclasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => ExtractSubclassInfo(ctx))
            .Where(info => info != null)
            .Select((info, _) => info!)
            .Collect();

        //生成TypeObjectConverterFactory
        context.RegisterSourceOutput(subclasses, (spc, infos) =>
        {
            GenerateFactory(spc, infos);
        });
    }

    //提取继承Type<A>的具体类信息
    private static SubclassInfo? ExtractSubclassInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol == null) return null;
        if (symbol.IsAbstract) return null;
        if (symbol.TypeKind != TypeKind.Class) return null;

        //向上查找BaseType检查是否直接或间接继承Type<A>
        var baseType = symbol.BaseType;
        while (baseType != null)
        {
            if (IsTypeA(baseType))
            {
                return CreateSubclassInfo(symbol, baseType);
            }
            baseType = baseType.BaseType;
        }
        return null;
    }

    //判断symbol是否是NetCraft.DataFixer.Types.Type<A>
    private static bool IsTypeA(INamedTypeSymbol symbol)
    {
        return symbol.Name == "Type"
            && symbol.ContainingNamespace?.ToDisplayString() == "NetCraft.DataFixer.Types"
            && symbol.Arity == 1
            && symbol.TypeKind == TypeKind.Class;
    }

    //创建子类信息
    private static SubclassInfo CreateSubclassInfo(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
    {
        //完全限定名格式包含外层类与命名空间
        var fullName = symbol.ToDisplayString(SymbolDisplayFormat);
        var containingType = symbol.ContainingType?.ToDisplayString(SymbolDisplayFormat) ?? "";
        //基类Type<X>中X的DisplayString用于判断A是否与子类泛型参数对应
        var baseArgDisplay = baseType.TypeArguments.Length == 1
            ? baseType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat)
            : "";

        var fields = symbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => !f.IsStatic && !f.IsConst)
            .Select(f => new FieldSpec(f.Name, f.Type.ToDisplayString(SymbolDisplayFormat)))
            .ToImmutableArray();
        var ctors = symbol.Constructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public)
            .Select(c => new CtorSpec(
                c.Parameters.Select(p => p.Type.ToDisplayString(SymbolDisplayFormat)).ToImmutableArray(),
                c.Parameters.Select(p => p.Name).ToImmutableArray()))
            .ToImmutableArray();

        return new SubclassInfo(
            fullName,
            symbol.Name,
            symbol.Arity,
            containingType,
            baseArgDisplay,
            IsDirectSubclass(symbol, baseType),
            fields,
            ctors);
    }

    //判断子类是否直接继承Type<子类第一个泛型参数>
    //直接继承的子类可以在AsObjectType<A>的switch中用子类<X>匹配
    private static bool IsDirectSubclass(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
    {
        if (symbol.Arity != 1) return false;
        if (baseType.TypeArguments.Length != 1) return false;
        var firstParam = symbol.TypeParameters[0];
        var baseArg = baseType.TypeArguments[0];
        //基类Type<X>中X必须是子类的第一个泛型参数
        return SymbolEqualityComparer.Default.Equals(baseArg, firstParam);
    }

    //生成TypeObjectConverterFactory代码
    private static void GenerateFactory(SourceProductionContext spc, ImmutableArray<SubclassInfo> infos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace NetCraft.DataFixer.Types;");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using NetCraft.DataFixer.Types.Templates;");
        sb.AppendLine();
        sb.AppendLine("//扫描发现 " + infos.Length + " 个Type<A>具体子类");
        sb.AppendLine("//直接继承Type<子类第一个泛型参数>的子类可生成switch case");
        sb.AppendLine("//间接继承如ListType<A>:Type<List<A>>需特殊处理");
        foreach (var info in infos.OrderBy(i => i.FullName))
        {
            var marker = info.IsDirectSubclass ? "[direct]" : "[indirect]";
            sb.AppendLine("//" + marker + " " + info.FullName + " arity=" + info.Arity + " base=" + info.BaseArgumentDisplay);
            foreach (var field in info.Fields)
            {
                sb.AppendLine("//  field " + field.Name + ": " + field.Type);
            }
            foreach (var ctor in info.Constructors)
            {
                sb.AppendLine("//  ctor(" + string.Join(", ", ctor.ParamTypes) + ")");
            }
        }
        sb.AppendLine();
        sb.AppendLine("public static class TypeObjectConverterFactory");
        sb.AppendLine("{");
        sb.AppendLine("    //AsObjectType把Type<A>转换为Type<object>");
        sb.AppendLine("    //A是object且type直接继承Type<object>时原实例直接返回");
        sb.AppendLine("    //否则用TypeObjectWrapper包装对齐Java类型擦除语义");
        sb.AppendLine("    public static Type<object> AsObjectType<A>(Type<A> type)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (type == null) return null!;");
        sb.AppendLine("        if (type is Type<object> direct) return direct;");
        sb.AppendLine("        return new TypeObjectWrapper(type);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    //AsObjectTypeUnsafe用Unsafe.As绕过运行时类型检查");
        sb.AppendLine("    //值类型A可能access violation因PrimitiveType<int>的MethodTable不含Type<object>虚方法槽");
        sb.AppendLine("    public static Type<object> AsObjectTypeUnsafe<A>(Type<A> type)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (type == null) return null!;");
        sb.AppendLine("        return System.Runtime.CompilerServices.Unsafe.As<Type<A>, Type<object>>(ref type);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("TypeObjectConverterFactory.g.cs", sb.ToString());
    }

    //SymbolDisplayFormat生成完全限定名包含外层类与命名空间
    private static readonly SymbolDisplayFormat SymbolDisplayFormat = new SymbolDisplayFormat(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    //子类信息记录netstandard2.0无IsExternalInit不能用record改用普通class
    private sealed class SubclassInfo
    {
        public string FullName { get; }
        public string ShortName { get; }
        public int Arity { get; }
        public string ContainingType { get; }
        public string BaseArgumentDisplay { get; }
        public bool IsDirectSubclass { get; }
        public ImmutableArray<FieldSpec> Fields { get; }
        public ImmutableArray<CtorSpec> Constructors { get; }

        public SubclassInfo(string fullName, string shortName, int arity, string containingType,
            string baseArgumentDisplay, bool isDirectSubclass,
            ImmutableArray<FieldSpec> fields, ImmutableArray<CtorSpec> constructors)
        {
            FullName = fullName;
            ShortName = shortName;
            Arity = arity;
            ContainingType = containingType;
            BaseArgumentDisplay = baseArgumentDisplay;
            IsDirectSubclass = isDirectSubclass;
            Fields = fields;
            Constructors = constructors;
        }
    }

    private sealed class FieldSpec
    {
        public string Name { get; }
        public string Type { get; }
        public FieldSpec(string name, string type) { Name = name; Type = type; }
    }

    private sealed class CtorSpec
    {
        public ImmutableArray<string> ParamTypes { get; }
        public ImmutableArray<string> ParamNames { get; }
        public CtorSpec(ImmutableArray<string> paramTypes, ImmutableArray<string> paramNames)
        {
            ParamTypes = paramTypes;
            ParamNames = paramNames;
        }
    }
}
