<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NetCraft\NetCraft.csproj" />
    <ProjectReference Include="..\NetCraft.Network\NetCraft.Network.csproj" />
    <ProjectReference Include="..\NetCraft.DataFixer\NetCraft.DataFixer.csproj" />
    <ProjectReference Include="..\NetCraft.Commands\NetCraft.Commands.csproj" />
    <ProjectReference Include="..\NetCraft.Gpu\NetCraft.Gpu.csproj" />
    <ProjectReference Include="..\NetCraft.Resources\NetCraft.Resources.csproj" />
    <ProjectReference Include="..\NetCraft.Tags\NetCraft.Tags.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
